--SELECT * FROM HDLAO_POWERBI_TEST.dbo.BUSINESS
--GO
--SELECT top 1000 * FROM HDLAO_CONSOLIDATION_V2.DBO.VIEW2_KN_CONSOLIDATED WHERE [year] = 2019 AND [month] = 12 AND acc_name LIKE 'R.B.I%'
--GO
--SELECT * FROM HDLAO_POWERBI_TEST.dbo.EXCHANGE_RATE
--GO
--SELECT top 1000 * FROM HDLAO_CONSOLIDATION_V2.dbo.VIEW2_KN_CONSOLIDATED
USE HDLAO_POWERBI_TEST
GO

 


--CODIGOS DE LAS CUENTAS
--'CA749100' --RBI ECLUD
--'74900'    --RBI INCLUD

 

SELECT top 1000 * FROM HDLAO_CONSOLIDATION_V2.DBO.VIEW2_KN_CONSOLIDATED WHERE [year] = 2019 AND [month] = 12 AND acc_id ='CA749100'--acc_name LIKE 'R.B.I%'
GO

 

SELECT top 1000 * FROM HDLAO_CONSOLIDATION_V2.DBO.VIEW2_KN_CONSOLIDATED WHERE [year] = 2019 AND [month] = 12 AND acc_id ='74900'--acc_name LIKE 'R.B.I%'
GO