USE HDLAO_POWERBI_TEST
USE HDLAO_CONSOLIDATION_V2
GO
INSERT INTO HDLAO_POWERBI_TEST.dbo.MONEDAS
	SELECT DISTINCT curr_id, curr_name FROM HDLAO_CONSOLIDATION_V2.dbo.VIEW2_KN_COUNTRY
GO
INSERT INTO HDLAO_POWERBI_TEST.dbo.TIPO_PERIODO
	SELECT DISTINCT per_id, per_name, per_abrev_name FROM HDLAO_CONSOLIDATION_V2.dbo.VIEW2_KN_CONSOLIDATED
GO
INSERT INTO HDLAO_POWERBI_TEST.dbo.TIPO_VALORES
	SELECT DISTINCT acc_id, acc_name FROM HDLAO_CONSOLIDATION_V2.dbo.VIEW2_KN_COUNTRY
GO